### ISSUE TITLE
Point update refactor

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/module-core-loraraw#28]
## Issue
the module is set up in a very static way where they payloads are always known.
We now need to allow for very dynamic payloads and unknown points. This requires a fair bit of refactoring.

## Current architecture
1. [get lora packet](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L93)
2. [get correct decoder](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L108)
3. [call decoder](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L112) and receive a fixed struct
4. [iterate over the struct and update the relevant points](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L284)

### Update Point Value
We need to move the responsibility of updating the points into the decoders. This way a decoder can update points one point at a time without knowing what points will be in the payload.
1. same
2. same
3. call decoder but only return an error
4. each decoder should call some function to update individual points
    ```
    updatePointValue(ioNumber string, name string, dev *model.Device, value float64)
    ```
    or something like that. It should still follow [this logic](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L318-L324) of getting the point by the `IoNumber` field but also create the point if it doesn't exist already using the `name` argument

This also means that we can remove all of the reflection stuff which is good! this code was terrible haha.
An example refactor of the [Droplet decoder](https://github.com/NubeIO/module-core-loraraw/blob/master/decoder/droplet.go#L42-L54) might look like this:
```
func DecodeDropletTH(data string, _ *LoRaDeviceDescription, dev *model.Device) error {
	temperature := dropletTemp(data)
	pressure := dropletPressure(data)
	humidity := dropletHumidity(data)
	voltage := dropletVoltage(data)
        updatePointValue("temperature", "temperature", dev, temperature)
        ...
}

```
This means all of the structs can probably be removed as well

### Auto Create Points
Instead of using this function to get a struct of all the points to auto-create points when adding a device, do the same shift of responsibility and instead make it a function that lets the decoder create the points as it wants

**Comment by maharjanaman** [comment]
@Shiny380 I went through the current implementation and have some questions,
- For the dynamic approach, should we create a device with the type `Dynamic`?
- For the feature where we want to have support for dynamic payloads, what types of payloads we’ll have? I mean is it 8 bytes or 12 bytes? Are there some test payloads that we can use for testing and how I should decode the device_id (normally I saw it will be the first 8 digits), name & value?
- Moreover, I need to not break existing ones. So, can you also send me the payloads for other types as well, so it will help me to do testing?

**Comment by Shiny380** [comment]
1. the dynamic decoder has been partially implemented already, this ticket doesn't need to worry about that part. The goal of this ticket it to make the existing ones dynamic in the way that they update their own individual points
2. again, this is implemented on another branch, not related for now
3. decode the device_id the same: first 8 chars
4. I'll provide some payloads and expected values soon

**Comment by Shiny380** [comment]
@maharjanaman see examples:
```
CBB272EAB20696263C0000DD000000041861
Type:         Droplet
Node ID:      CBB272EA
Temperature:  17.31˚C
Pressure:     987.80hPa
Humidity:     59%
Movement:     false
Light:        0 lux
Voltage:      4.46v
```
```
36B2A847DE0698263D0000E9000000D91E5C

Type:         Droplet
Node ID:      36B2A847
Temperature:  18.03˚C
Pressure:     988.10hPa
Humidity:     56%
Movement:     false
Light:        0 lux
Voltage:      4.78v
```
```
1AB22D4F2006C6263D0200DB000000E81A61

Type:         Droplet
Node ID:      1AB22D4F
Temperature:  15.68˚C
Pressure:     992.60hPa
Humidity:     61%
Movement:     false
Light:        2 lux
Voltage:      4.38v
```
```
17AC7BB100000000FF03FF03FF03FF014B5F

Type:             Micro Edge
Node ID          : 17AC7BB1
Analog 1         : 1023
Analog 2         : 1023
Analog 3         : 1023
Pulses           : 0
```
```
55ACA79B00000000FF03FF03FF03FF013F64

Type:             Micro Edge
Node ID          : 55ACA79B
Analog 1         : 1023
Analog 2         : 1023
Analog 3         : 1023
Pulses           : 0
```

_note:_ I don't have the rssi and snr expected values but you can determine what these should be
