### ISSUE TITLE
[Feature] Decryption Refactor

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/module-core-loraraw#32]
Decryption responsibility for LoRaRAW Unique needs to be move from Driver-LoRa to here.
Decryption needs to happen on _per device_ basis.
Requires https://github.com/NubeIO/driver-lora/issues/9 first

1. Update the device schema to accept a Hex based string as the key
    - **MUST** be 32 chars long
    - make sure it's set to `secret` so it's not displayed as plain text
2. implement decryption as in [Driver-LoRa](https://github.com/NubeIO/driver-lora/blob/master/src/loRaRaw.py#L57)
3. use the device key, revert to config `default_key` if no key exists

**Comment by Shiny380** [comment]
@maharjanaman when it comes to this task, please leave the existing functionality in there and provide a config called `decryptionDisabled` (default `false`). If this is `true` then use the existing/old functionality to decrypt the packets

**Comment by maharjanaman** [comment]
I've set the decryption part in the module but have a few questions,
> use the device key, revert to config default_key if no key exists

What is the device key? Is this a key that is statically defined in `driver-lora`?

> @maharjanaman when it comes to this task, please leave the existing functionality in there and provide a config called decryptionDisabled (default false). If this is true then use the existing/old functionality to decrypt the packets

The module didn't have the decryption. Did you mean the decoding?

**Comment by Shiny380** [comment]
> What is the device key? Is this a key that is statically defined in driver-lora?

The device key as defined in 1. in the issue description.
`1. Update the device schema to accept a Hex based string as the key`.
Try and use an existing string field in the device model for this.
If this string is does not exist and is not a valid 32-char hex string, then resort to the `DefaultKey` in the config

---

> The module didn't have the decryption. Did you mean the decoding?

ah yes sorry, I just mean skip the new decryption part

**Comment by Shiny380** [comment]
Moved to Jira
https://nube-io.atlassian.net/browse/GEN1-21
