### ISSUE TITLE
[Bug] Account for CMAC difference in driver-lora

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/module-core-loraraw#34]
driver-lora has been printing data slightly wrong this whole time and we need to align it to existing firmware. See that ticket [here](https://github.com/NubeIO/driver-lora/issues/10).

This small refactor will require several changes
1. First, only send the data section to the decoder.
    This means removing the device address, inner header (4 + 3 = 7) from the start and the CMAC and the RSSI, SNR bytes on the end (4 + 2 = 6)
    so something like `decode(data[7:-6], ...)`
    (Note this is bytes not hex, so double if accounting for hex string).

    You will need to account for this difference in _**EACH**_ decoder as the location of each byte will be different now.

2. Remove the RSSI and SNR decoding and writing from **_EACH_** decoder and do it in one place instead: AFTER the main decoding and IF the main decoding returns successfully. i.e. [here](https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L114)

**Comment by maharjanaman** [comment]
> This means removing the device address, inner header (4 + 3 = 7) from the start and the CMAC and the RSSI, SNR bytes on the end (4 + 2 = 6)

@Shiny380 Don't the payloads for Micro Edge from this comment https://github.com/NubeIO/module-core-loraraw/issues/28#issuecomment-2196103555 have ***inner header***? The current implementation for Micro Edge does not account for ***inner header*** and data after the address is decoded as value.

Also, if we add CMAC in driver-lora the total addition bytes would be [4 (cmac) + 2 (RSSI) + 2 (snr)] = 8 at the end, right?

I tried extracting values from the above payloads after removing these bytes from the front and end but the remaining bytes were not sufficient (maybe because of the inner header & cmac). Do you have some test data?

**Comment by maharjanaman** [comment]
@Shiny380 I've created a draft PR for this issue. The PR is in draft as I'm still confused about the following,
- Will the method to check payload length be still valid for Micro Edge and Droplet?
  ```
  func CheckPayloadLength(data string) bool {
	dl := len(data)
	return dl == 36 || dl == 32 || dl == 44
  }
  ```
- Are payload for Micro Edge and Droplet similar to Ziphydrotap/Rubix? Where,
  In Hex,
  - First 8 char is address
  - Next 2 is options
  - Next 2 is nonce
  - Next 2 is data length
  - Next are payload
      - First 2 is payload type
  - Last 8 are CMAC, RSSI and SNR
  
  Based on this, I might need to adjust bytes for decoders.

**Comment by Shiny380** [comment]
Ah sorry I forgot to account for that. We can detect 2 scenarios like so:
(taken from [here](https://github.com/NubeIO/driver-lora/blob/master/src/serialBridge.py#L33-L38))
```
        # +4 for HEADER, +4 for CMAC, +1 for RSSI and +1 for SNR. total = 10 bytes (4+4+1+1)
        if length % 16 == (LORA_RAW_HEADER_LEN + LORA_RAW_CMAC_LEN + RSSI_LEN + SNR_LEN):
            # LoRaRAW Unique device
        else:
            # Legacy device (Droplet, MicroEdge)
```

If LoRaRAW device, do new approach, else lets just keep the droplet and microedge decoders as they are. the old legacy devices suck and are a mess haha best to not touch them :sweat_smile:
